spring.application.name=nasa-apod
spring.main.web-application-type=none

# NASA API Key (using DEMO_KEY by default)
nasa.api.key=DEMO_KEY

# Directory to save images (it will be created if it doesn't exist)
nasa.download.dir=nasa-images
